### ISSUE TITLE
Error Handling is not done properly

### ISSUE THREAD

**Issue by Ashik155** [hapijs/catbox-memory#89]
### Runtime

nodejs

### Runtime version

16.15

### Module version

4.1.1

### Used with

hapi server cache. 

### Any other relevant information

<img width="381" alt="image" src="https://github.com/hapijs/catbox-memory/assets/52832896/67aabe38-7e44-4635-ad44-b487a85a72c2">
Recentyl we have noticed that this error is not getting handled properly. 

### What are you trying to achieve or the steps to reproduce?

a proper error handling and following that next steps for smooth processing 

### What was the result you got?

Cache size limit reached, stack: Error: Cache size limit reached\n    at module.exports.internals.Connection.set (/opt/bba/server/node_modules/@hapi/catbox-memory/lib/index.js:184:19)\n    at module.exports.set (/opt/bba/server/node_modules/@hapi/catbox/lib/client.js:91:31)\n    at module.exports.internals.Policy.set (/opt/bba/server/node_modules/@hapi/catbox/lib/policy.js:298:31)\n    at internals.onPreResponse (/opt/bba/server/node_modules/@hapi/yar/lib/index.js:307:17)\n    at async module.exports.internals.Manager.execute (/opt/bba/server/node_modules/@hapi/hapi/lib/toolkit.js:45:28)\n    at async Request._invoke (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:339:30)\n    at async Request._postCycle (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:402:32)\n    at async Request._reply (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:381:9)\n"}

### What result did you expect?

It should provide better error handling

**Comment by Marsup** [comment]
Please provide a full reproduction for your issue. Note that duplicating your issue is neither necessary nor helpful.
